# Application
spring.application.name=practicafarmacia

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://your-host:your-port/your-database?prepareThreshold=0
spring.datasource.username=your-username
spring.datasource.password=your-password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=farmacia